version: '3'
services:
  mongodb-lab:
    container_name: mongodb-lab
    image: mongo:6.0.2-focal
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin